/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OirRouteImport } from './routes/oir'
import { Route as IndexRouteImport } from './routes/index'

const OirRoute = OirRouteImport.update({
  id: '/oir',
  path: '/oir',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oir': typeof OirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oir': typeof OirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oir': typeof OirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oir'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oir'
  id: '__root__' | '/' | '/oir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OirRoute: typeof OirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oir': {
      id: '/oir'
      path: '/oir'
      fullPath: '/oir'
      preLoaderRoute: typeof OirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OirRoute: OirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
