/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CitasRouteImport } from './routes/citas'
import { Route as LupaRouteImport } from './routes/lupa'
import { Route as OirRouteImport } from './routes/oir'
import { Route as PanicoRouteImport } from './routes/panico'
import { Route as PastillasRouteImport } from './routes/pastillas'
import { Route as UbicacionRouteImport } from './routes/ubicacion'
import { Route as VincularRouteImport } from './routes/vincular'
import { Route as AuthenticatedFamilyIndexRouteImport } from './routes/_authenticated/family.index'
import { Route as AuthenticatedFamilyHistoricoRouteImport } from './routes/_authenticated/family.historico'
import { Route as AuthenticatedFamilyHoyRouteImport } from './routes/_authenticated/family.hoy'
import { Route as AuthenticatedFamilyPerfilRouteImport } from './routes/_authenticated/family.perfil'
import { Route as AuthenticatedFamilyVincularRouteImport } from './routes/_authenticated/family.vincular'
import { Route as AuthenticatedFamilyEditarIdRouteImport } from './routes/_authenticated/family.editar.$id'
import { Route as AuthenticatedFamilyPersonaIdRouteImport } from './routes/_authenticated/family.persona.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CitasRoute = CitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaRoute = LupaRouteImport.update({
  id: '/lupa',
  path: '/lupa',
  getParentRoute: () => rootRouteImport,
} as any)
const OirRoute = OirRouteImport.update({
  id: '/oir',
  path: '/oir',
  getParentRoute: () => rootRouteImport,
} as any)
const PanicoRoute = PanicoRouteImport.update({
  id: '/panico',
  path: '/panico',
  getParentRoute: () => rootRouteImport,
} as any)
const PastillasRoute = PastillasRouteImport.update({
  id: '/pastillas',
  path: '/pastillas',
  getParentRoute: () => rootRouteImport,
} as any)
const UbicacionRoute = UbicacionRouteImport.update({
  id: '/ubicacion',
  path: '/ubicacion',
  getParentRoute: () => rootRouteImport,
} as any)
const VincularRoute = VincularRouteImport.update({
  id: '/vincular',
  path: '/vincular',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFamilyIndexRoute =
  AuthenticatedFamilyIndexRouteImport.update({
    id: '/family/',
    path: '/family/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyHistoricoRoute =
  AuthenticatedFamilyHistoricoRouteImport.update({
    id: '/family/historico',
    path: '/family/historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyHoyRoute = AuthenticatedFamilyHoyRouteImport.update({
  id: '/family/hoy',
  path: '/family/hoy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyPerfilRoute =
  AuthenticatedFamilyPerfilRouteImport.update({
    id: '/family/perfil',
    path: '/family/perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyVincularRoute =
  AuthenticatedFamilyVincularRouteImport.update({
    id: '/family/vincular',
    path: '/family/vincular',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyEditarIdRoute =
  AuthenticatedFamilyEditarIdRouteImport.update({
    id: '/family/editar/$id',
    path: '/family/editar/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyPersonaIdRoute =
  AuthenticatedFamilyPersonaIdRouteImport.update({
    id: '/family/persona/$id',
    path: '/family/persona/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/citas': typeof CitasRoute
  '/lupa': typeof LupaRoute
  '/oir': typeof OirRoute
  '/panico': typeof PanicoRoute
  '/pastillas': typeof PastillasRoute
  '/ubicacion': typeof UbicacionRoute
  '/vincular': typeof VincularRoute
  '/family/historico': typeof AuthenticatedFamilyHistoricoRoute
  '/family/hoy': typeof AuthenticatedFamilyHoyRoute
  '/family/perfil': typeof AuthenticatedFamilyPerfilRoute
  '/family/vincular': typeof AuthenticatedFamilyVincularRoute
  '/family/': typeof AuthenticatedFamilyIndexRoute
  '/family/editar/$id': typeof AuthenticatedFamilyEditarIdRoute
  '/family/persona/$id': typeof AuthenticatedFamilyPersonaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/citas': typeof CitasRoute
  '/lupa': typeof LupaRoute
  '/oir': typeof OirRoute
  '/panico': typeof PanicoRoute
  '/pastillas': typeof PastillasRoute
  '/ubicacion': typeof UbicacionRoute
  '/vincular': typeof VincularRoute
  '/family/historico': typeof AuthenticatedFamilyHistoricoRoute
  '/family/hoy': typeof AuthenticatedFamilyHoyRoute
  '/family/perfil': typeof AuthenticatedFamilyPerfilRoute
  '/family/vincular': typeof AuthenticatedFamilyVincularRoute
  '/family': typeof AuthenticatedFamilyIndexRoute
  '/family/editar/$id': typeof AuthenticatedFamilyEditarIdRoute
  '/family/persona/$id': typeof AuthenticatedFamilyPersonaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/citas': typeof CitasRoute
  '/lupa': typeof LupaRoute
  '/oir': typeof OirRoute
  '/panico': typeof PanicoRoute
  '/pastillas': typeof PastillasRoute
  '/ubicacion': typeof UbicacionRoute
  '/vincular': typeof VincularRoute
  '/_authenticated/family/historico': typeof AuthenticatedFamilyHistoricoRoute
  '/_authenticated/family/hoy': typeof AuthenticatedFamilyHoyRoute
  '/_authenticated/family/perfil': typeof AuthenticatedFamilyPerfilRoute
  '/_authenticated/family/vincular': typeof AuthenticatedFamilyVincularRoute
  '/_authenticated/family/': typeof AuthenticatedFamilyIndexRoute
  '/_authenticated/family/editar/$id': typeof AuthenticatedFamilyEditarIdRoute
  '/_authenticated/family/persona/$id': typeof AuthenticatedFamilyPersonaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/citas'
    | '/lupa'
    | '/oir'
    | '/panico'
    | '/pastillas'
    | '/ubicacion'
    | '/vincular'
    | '/family/historico'
    | '/family/hoy'
    | '/family/perfil'
    | '/family/vincular'
    | '/family/'
    | '/family/editar/$id'
    | '/family/persona/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/citas'
    | '/lupa'
    | '/oir'
    | '/panico'
    | '/pastillas'
    | '/ubicacion'
    | '/vincular'
    | '/family/historico'
    | '/family/hoy'
    | '/family/perfil'
    | '/family/vincular'
    | '/family'
    | '/family/editar/$id'
    | '/family/persona/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/citas'
    | '/lupa'
    | '/oir'
    | '/panico'
    | '/pastillas'
    | '/ubicacion'
    | '/vincular'
    | '/_authenticated/family/historico'
    | '/_authenticated/family/hoy'
    | '/_authenticated/family/perfil'
    | '/_authenticated/family/vincular'
    | '/_authenticated/family/'
    | '/_authenticated/family/editar/$id'
    | '/_authenticated/family/persona/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CitasRoute: typeof CitasRoute
  LupaRoute: typeof LupaRoute
  OirRoute: typeof OirRoute
  PanicoRoute: typeof PanicoRoute
  PastillasRoute: typeof PastillasRoute
  UbicacionRoute: typeof UbicacionRoute
  VincularRoute: typeof VincularRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citas': {
      id: '/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof CitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa': {
      id: '/lupa'
      path: '/lupa'
      fullPath: '/lupa'
      preLoaderRoute: typeof LupaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oir': {
      id: '/oir'
      path: '/oir'
      fullPath: '/oir'
      preLoaderRoute: typeof OirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panico': {
      id: '/panico'
      path: '/panico'
      fullPath: '/panico'
      preLoaderRoute: typeof PanicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pastillas': {
      id: '/pastillas'
      path: '/pastillas'
      fullPath: '/pastillas'
      preLoaderRoute: typeof PastillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ubicacion': {
      id: '/ubicacion'
      path: '/ubicacion'
      fullPath: '/ubicacion'
      preLoaderRoute: typeof UbicacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vincular': {
      id: '/vincular'
      path: '/vincular'
      fullPath: '/vincular'
      preLoaderRoute: typeof VincularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/family/': {
      id: '/_authenticated/family/'
      path: '/family'
      fullPath: '/family/'
      preLoaderRoute: typeof AuthenticatedFamilyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/historico': {
      id: '/_authenticated/family/historico'
      path: '/family/historico'
      fullPath: '/family/historico'
      preLoaderRoute: typeof AuthenticatedFamilyHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/hoy': {
      id: '/_authenticated/family/hoy'
      path: '/family/hoy'
      fullPath: '/family/hoy'
      preLoaderRoute: typeof AuthenticatedFamilyHoyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/perfil': {
      id: '/_authenticated/family/perfil'
      path: '/family/perfil'
      fullPath: '/family/perfil'
      preLoaderRoute: typeof AuthenticatedFamilyPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/vincular': {
      id: '/_authenticated/family/vincular'
      path: '/family/vincular'
      fullPath: '/family/vincular'
      preLoaderRoute: typeof AuthenticatedFamilyVincularRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/editar/$id': {
      id: '/_authenticated/family/editar/$id'
      path: '/family/editar/$id'
      fullPath: '/family/editar/$id'
      preLoaderRoute: typeof AuthenticatedFamilyEditarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/persona/$id': {
      id: '/_authenticated/family/persona/$id'
      path: '/family/persona/$id'
      fullPath: '/family/persona/$id'
      preLoaderRoute: typeof AuthenticatedFamilyPersonaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFamilyHistoricoRoute: typeof AuthenticatedFamilyHistoricoRoute
  AuthenticatedFamilyHoyRoute: typeof AuthenticatedFamilyHoyRoute
  AuthenticatedFamilyPerfilRoute: typeof AuthenticatedFamilyPerfilRoute
  AuthenticatedFamilyVincularRoute: typeof AuthenticatedFamilyVincularRoute
  AuthenticatedFamilyIndexRoute: typeof AuthenticatedFamilyIndexRoute
  AuthenticatedFamilyEditarIdRoute: typeof AuthenticatedFamilyEditarIdRoute
  AuthenticatedFamilyPersonaIdRoute: typeof AuthenticatedFamilyPersonaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFamilyHistoricoRoute: AuthenticatedFamilyHistoricoRoute,
  AuthenticatedFamilyHoyRoute: AuthenticatedFamilyHoyRoute,
  AuthenticatedFamilyPerfilRoute: AuthenticatedFamilyPerfilRoute,
  AuthenticatedFamilyVincularRoute: AuthenticatedFamilyVincularRoute,
  AuthenticatedFamilyIndexRoute: AuthenticatedFamilyIndexRoute,
  AuthenticatedFamilyEditarIdRoute: AuthenticatedFamilyEditarIdRoute,
  AuthenticatedFamilyPersonaIdRoute: AuthenticatedFamilyPersonaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CitasRoute: CitasRoute,
  LupaRoute: LupaRoute,
  OirRoute: OirRoute,
  PanicoRoute: PanicoRoute,
  PastillasRoute: PastillasRoute,
  UbicacionRoute: UbicacionRoute,
  VincularRoute: VincularRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
