/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitasRouteImport } from './routes/citas'
import { Route as LupaRouteImport } from './routes/lupa'
import { Route as OirRouteImport } from './routes/oir'
import { Route as PanicoRouteImport } from './routes/panico'
import { Route as PastillasRouteImport } from './routes/pastillas'
import { Route as UbicacionRouteImport } from './routes/ubicacion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitasRoute = CitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaRoute = LupaRouteImport.update({
  id: '/lupa',
  path: '/lupa',
  getParentRoute: () => rootRouteImport,
} as any)
const OirRoute = OirRouteImport.update({
  id: '/oir',
  path: '/oir',
  getParentRoute: () => rootRouteImport,
} as any)
const PanicoRoute = PanicoRouteImport.update({
  id: '/panico',
  path: '/panico',
  getParentRoute: () => rootRouteImport,
} as any)
const PastillasRoute = PastillasRouteImport.update({
  id: '/pastillas',
  path: '/pastillas',
  getParentRoute: () => rootRouteImport,
} as any)
const UbicacionRoute = UbicacionRouteImport.update({
  id: '/ubicacion',
  path: '/ubicacion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citas': typeof CitasRoute
  '/lupa': typeof LupaRoute
  '/oir': typeof OirRoute
  '/panico': typeof PanicoRoute
  '/pastillas': typeof PastillasRoute
  '/ubicacion': typeof UbicacionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citas': typeof CitasRoute
  '/lupa': typeof LupaRoute
  '/oir': typeof OirRoute
  '/panico': typeof PanicoRoute
  '/pastillas': typeof PastillasRoute
  '/ubicacion': typeof UbicacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citas': typeof CitasRoute
  '/lupa': typeof LupaRoute
  '/oir': typeof OirRoute
  '/panico': typeof PanicoRoute
  '/pastillas': typeof PastillasRoute
  '/ubicacion': typeof UbicacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/citas' | '/lupa' | '/oir' | '/panico' | '/pastillas' | '/ubicacion'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/citas' | '/lupa' | '/oir' | '/panico' | '/pastillas' | '/ubicacion'
  id:
    | '__root__'
    | '/'
    | '/citas'
    | '/lupa'
    | '/oir'
    | '/panico'
    | '/pastillas'
    | '/ubicacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitasRoute: typeof CitasRoute
  LupaRoute: typeof LupaRoute
  OirRoute: typeof OirRoute
  PanicoRoute: typeof PanicoRoute
  PastillasRoute: typeof PastillasRoute
  UbicacionRoute: typeof UbicacionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citas': {
      id: '/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof CitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa': {
      id: '/lupa'
      path: '/lupa'
      fullPath: '/lupa'
      preLoaderRoute: typeof LupaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oir': {
      id: '/oir'
      path: '/oir'
      fullPath: '/oir'
      preLoaderRoute: typeof OirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panico': {
      id: '/panico'
      path: '/panico'
      fullPath: '/panico'
      preLoaderRoute: typeof PanicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pastillas': {
      id: '/pastillas'
      path: '/pastillas'
      fullPath: '/pastillas'
      preLoaderRoute: typeof PastillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ubicacion': {
      id: '/ubicacion'
      path: '/ubicacion'
      fullPath: '/ubicacion'
      preLoaderRoute: typeof UbicacionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitasRoute: CitasRoute,
  LupaRoute: LupaRoute,
  OirRoute: OirRoute,
  PanicoRoute: PanicoRoute,
  PastillasRoute: PastillasRoute,
  UbicacionRoute: UbicacionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
